# Generated by Django 3.1 on 2020-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='treeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sciname', models.CharField(max_length=50)),
                ('localname1', models.CharField(max_length=50)),
                ('localname2', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('uses', models.CharField(max_length=500)),
                ('maxheight', models.FloatField()),
                ('lifespan', models.IntegerField()),
                ('timbervalue', models.IntegerField()),
                ('avgtreeweight', models.IntegerField()),
                ('matureage', models.IntegerField()),
                ('req_soil', models.CharField(max_length=50)),
                ('req_temp', models.CharField(max_length=50)),
                ('req_water', models.CharField(max_length=50)),
                ('req_rain', models.CharField(max_length=50)),
                ('req_alt', models.CharField(max_length=50)),
                ('req_girth', models.CharField(max_length=50)),
                ('req_other', models.CharField(max_length=50)),
                ('treedesc', models.CharField(max_length=300)),
                ('treepic', models.ImageField(default='treepic.jpg', upload_to='images/')),
                ('trunkdesc', models.CharField(max_length=300)),
                ('trunkpic', models.ImageField(default='trunkpic.jpg', upload_to='images/')),
                ('leavesesc', models.CharField(max_length=300)),
                ('leavespic', models.ImageField(default='leavespic.jpg', upload_to='images/')),
                ('flowerdesc', models.CharField(max_length=300)),
                ('flowerpic', models.ImageField(default='flowerpic.jpg', upload_to='images/')),
                ('other1desc', models.CharField(max_length=300)),
                ('other1pic', models.ImageField(default='other1pic.jpg', upload_to='images/')),
                ('other2desc', models.CharField(max_length=300)),
                ('other2pic', models.ImageField(default='other2pic.jpg', upload_to='images/')),
            ],
        ),
    ]
