# Generated by Django 3.1 on 2020-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeinfo',
            name='leavesesc',
        ),
        migrations.AddField(
            model_name='treeinfo',
            name='leavesdesc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='avgtreeweight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='flowerdesc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='flowerpic',
            field=models.ImageField(blank=True, default='flowerpic.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='leavespic',
            field=models.ImageField(blank=True, default='leavespic.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='lifespan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='localname2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='matureage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='maxheight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='other1desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='other1pic',
            field=models.ImageField(blank=True, default='other1pic.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='other2desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='other2pic',
            field=models.ImageField(blank=True, default='other2pic.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='req_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='req_girth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='req_other',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='req_rain',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='req_soil',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='req_temp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='req_water',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='timbervalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='treedesc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='trunkdesc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='trunkpic',
            field=models.ImageField(blank=True, default='trunkpic.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='treeinfo',
            name='uses',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
